<div style="background: #000;
            color: #FFF;
            margin: 0px;
                padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Lab</h1>
</div>


# Question 1 

We'd like to create a function that takes a number and outputs the number with it's ordinal indictator (e.g. 1 -> 1st, 2 -> 2nd, and so on).

Walk us through the steps we might need to take. DO NOT write any code. Try writing what we call "pseudocode".

# Exercise 1

Create a function that takes two parameters and returns a list.

In [2]:
def myFunction(val1, val2):
  my_list = [val1, val2]
  return my_list

print(myFunction(2, "red"))

[2, 'red']


# Exercise 2


Create a function that will return the list of square roots from numbers from 1 to `n` (where `n` is the input)



In [16]:
import numpy as np

def squareRoots(n):
  my_list = []
  for i in range(1, n + 1):
    my_list.append(np.sqrt(i))
  
  return my_list

squareRoots(5)

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]

# Exercise 3

Create a function that takes `n` as the input and returns a `n`x`n` matrix where all the values are zeros. 

In [9]:
import numpy as np

def matrix(n):
  return np.zeros((n, n))

matrix(3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Exercise 4

Find an exercise from a previous lab and convert it into a function demonstrating the ability to define the function and call it using the correct arguments/keywords

In [ ]:
import random

def numberSearch(num):
  number = random.randint(0, 100)
  while number != num:
    number = random.randint(0, 100)
    print("Current number in loop:", number)
  print("Number found, loop exited...")

user = int(input("Enter a number 0 - 100 to search: "))
numberSearch(user)

# Bonus:
    
Create a function that has a function within. Demonstrate how you might use this function in a real world application.

In [15]:
def createTriangle(val):
  triangle = []
  while val >= 0:
    triangle.append(val)
    print(triangle)
    val -= 1

def testFunction (element):
  if type(element) == int:
    createTriangle(element)
  else:
    return "You did not pass an integer value."

testFunction("red")

'You did not pass an integer value.'